services:
  triton_server:
    image: triton-signature-server:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env
