---
blank_issues_enabled: True
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/samuellimabraz/https://github.com/tech4ai/discussions
    about: Please ask and answer questions here.
  
  - name: 🌐 Website
    url: https://www.tech4.ai/contact
    about: Ask on the website.
