name: "postprocess"
backend: "python"

max_batch_size: 1

input {
  name: "postprocess_input"
  data_type: TYPE_FP32
  dims: [5, -1]
}
input {
  name: "confidence_threshold"
  data_type: TYPE_FP16
  dims: [1]
}
input {
  name: "iou_threshold"
  data_type: TYPE_FP16
  dims: [1]
}

output {
  name: "detection_result"
  data_type: TYPE_FP16
  dims: [-1, 5]
}

dynamic_batching {
  max_queue_delay_microseconds: 150
}

instance_group {
  count: 1
  kind: KIND_CPU
}
