name: "[STG] Deploy to Azure Container App"

run-name: "[STG] Deploy by ${{ github.actor }}"

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - release/v*
      - hotfix/v*
  workflow_dispatch:

jobs:
  environment:
    name: "Load Environment Variables"
    runs-on: ubuntu-latest
    environment: Staging
    outputs:
      app_name: ${{ vars.APP_NAME }}
      group_name: ${{ vars.GROUP_NAME }}
    steps:
      - name: "Load Environment Variables"
        id: vars
        shell: bash
        run: |
          echo "Loading Environment Variables"

  copy-data:
    needs: environment
    uses: tech4ai/t4ai-signature-detect-server/.github/workflows/reusable/cd-azure-storage-copy.yaml@develop
    with:
      environment: Staging
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_STAGING }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_STAGING }}
      ORIGIN_STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT_DEVELOP }}
      TARGET_STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT_STAGING }}
      ORIGIN_CONTAINER_NAME: ${{ vars.BLOB_CONTAINER_NAME_DEVELOP }}
      TARGET_CONTAINER_NAME: ${{ vars.BLOB_CONTAINER_NAME_STAGING }}

  call-deploy:
    needs: copy-data 
    uses: tech4ai/t4ai-signature-detect-server/.github/workflows/reusable/cd-docker-azure.yaml@develop
    with:
      container-app-name: ${{ needs.environment.outputs.app_name }}
      resource-group: ${{ needs.environment.outputs.group_name }}
      environment: Staging
      registry-url: ${{ vars.REGISTRY_USERNAME_STAGING }}.azurecr.io
    secrets:
      REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME_STAGING }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD_STAGING }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_STAGING }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_STAGING }}
