name: "Copy Storage Contents"
on:
  workflow_call:
    inputs:
      environment:
        description: "Ambiente"
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        description: "ID do client da Azure"
        required: true
      AZURE_TENANT_ID:
        description: "ID do tenant da Azure"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "ID da subscription da Azure"
        required: true
      ORIGIN_STORAGE_ACCOUNT:
        description: "Conta de armazenamento de origem"
        required: true
      TARGET_STORAGE_ACCOUNT:
        description: "Conta de armazenamento de destino"
        required: true
      ORIGIN_CONTAINER_NAME:
        description: "Nome do container de origem"
        required: true
      TARGET_CONTAINER_NAME:
        description: "Nome do container de destino"
        required: true

jobs:
  copy-storage:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment: ${{ inputs.environment }}

    env:
      ORIGIN_SAS: ""
      DESTINATION_SAS: ""

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate SAS Token for Origin and Destination
        run: |
          ORIGIN_SAS=$(az storage container generate-sas \
            --name ${{ secrets.ORIGIN_CONTAINER_NAME }} \
            --account-name ${{ secrets.ORIGIN_STORAGE_ACCOUNT }} \
            --permissions rl \
            --expiry $(date -u -d '1 hour' '+%Y-%m-%dT%H:%M:%SZ') \
            --auth-mode login \
            --as-user \
            --output tsv)

          DESTINATION_SAS=$(az storage container generate-sas \
            --name ${{ secrets.TARGET_CONTAINER_NAME }} \
            --account-name ${{ secrets.TARGET_STORAGE_ACCOUNT }} \
            --permissions rlw \
            --expiry $(date -u -d '1 hour' '+%Y-%m-%dT%H:%M:%SZ') \
            --auth-mode login \
            --as-user \
            --output tsv)

          echo "ORIGIN_SAS=$ORIGIN_SAS" >> $GITHUB_ENV
          echo "DESTINATION_SAS=$DESTINATION_SAS" >> $GITHUB_ENV

      - name: Install AzCopy
        run: |
          wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
          tar -xvf azcopy.tar.gz
          sudo mv azcopy_linux_amd64_*/azcopy /usr/local/bin/
  
      - name: Copy Storage Data using SAS Tokens
        run: |
          azcopy copy "https://${{ secrets.ORIGIN_STORAGE_ACCOUNT }}.blob.core.windows.net/${{ secrets.ORIGIN_CONTAINER_NAME }}?${{ env.ORIGIN_SAS }}" \
                      "https://${{ secrets.TARGET_STORAGE_ACCOUNT }}.blob.core.windows.net/${{ secrets.TARGET_CONTAINER_NAME }}?${{ env.DESTINATION_SAS }}" \
                      --recursive