name: Trigger auto deployment for t4ai-triton-capp-staging

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/t4ai-triton-capp-staging-AutoDeployTrigger-72e47b96-1e43-4d6c-a734-e40d84f619f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.T4AITRITONCAPPSTAGING_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.T4AITRITONCAPPSTAGING_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.T4AITRITONCAPPSTAGING_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.T4AITRITONCAPPSTAGING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.T4AITRITONCAPPSTAGING_REGISTRY_PASSWORD }}
          containerAppName: t4ai-triton-capp-staging
          resourceGroup: t4ai-inference-gateway-rg-staging
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


